### ISSUE TITLE
add nextpnr

### ISSUE THREAD

**Issue by dvc94ch** [FPGAwars/toolchain-icestorm#67]

**Comment by mmicko** [comment]
@dvc94ch Working on ecp5 support and also getting all tools to latest. Feel free to contact me directly on this (my email is visible on profile page)

**Comment by dvc94ch** [comment]
that is awesome, thanks!

I repackaged the apio packages for npm here: https://github.com/electron-lang/electron-vendor

any chance to get ngspice packaged in apio? or alternatively I can contribute the linux part, don't know about osx or windows.

**Comment by Jesus89** [comment]
Awesome work @dvc94ch :eyes: 

You can work on the scripts to build ngspice for Linux and then try to make them work for the other OS.

**Comment by mmicko** [comment]
In order to work on all platforms independent of specific distribution (for linux case) all binaries for apio are distributed as static linked binaries, they are bit bigger but it solves lot of problem. Would give my priority for solving first ecp5 support and putting first all to latest, then can look at ngspice

**Comment by pwmarcz** [comment]
Having nextpnr packaged here would be awesome. Anything I could do to help?

**Comment by Obijuan** [comment]
Closing this issue
